service: icebreakerbot
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  icebreakerbot:
    handler: bin/icebreakerbot
    events:
      - http:
          path: /
          method: get
