on:
  schedule:
    - cron:  '0 12 * * 1-5'
  push:
    branches: [master]
name: Deploy
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v1
      - run: make test
      - run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
